index:
    path: /
    controller: App\Controller\NewsController::list

article_item:
    path: /article/{article}
    controller: App\Controller\NewsController::item
    requirements:
        article: \d+
